# Generated by Django 5.2.5 on 2025-10-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0013_alter_divisa_simbolo'),
        ('tauser', '0001_initial'),
        ('transacciones', '0007_transaccion_cambio_cotizacion_notificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('reserva', 'Reserva'), ('liberacion', 'Liberación'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, default='', help_text='Descripción del motivo del movimiento', verbose_name='Motivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.divisa', verbose_name='Divisa')),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tauser.tauser', verbose_name='Tauser')),
                ('transaccion', models.ForeignKey(blank=True, help_text='Transacción asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transacciones.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStockDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, help_text='Cantidad de billetes/monedas de esta denominación', verbose_name='Cantidad')),
                ('denominacion', models.IntegerField(default=0, help_text='Denominación del billete/moneda', verbose_name='Denominación')),
                ('movimiento_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='stock.movimientostock', verbose_name='Movimiento de Stock')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento de Stock',
                'verbose_name_plural': 'Detalles de Movimientos de Stock',
                'ordering': ['-denominacion'],
                'unique_together': {('movimiento_stock', 'denominacion')},
            },
        ),
        migrations.CreateModel(
            name='StockDivisaTauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.IntegerField(default=0, help_text='Denominación del billete/moneda', verbose_name='Denominación')),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible en stock', verbose_name='Stock Disponible')),
                ('stock_reservado', models.IntegerField(default=0, help_text='Cantidad reservada para transacciones pendientes', verbose_name='Stock Reservado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('divisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.divisa', verbose_name='Divisa')),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tauser.tauser', verbose_name='Tauser')),
            ],
            options={
                'verbose_name': 'Stock de Divisa por Tauser',
                'verbose_name_plural': 'Stocks de Divisas por Tauser',
                'ordering': ['tauser__nombre', 'divisa__codigo', 'denominacion'],
                'unique_together': {('tauser', 'divisa', 'denominacion')},
            },
        ),
    ]
