# Generated by Django 5.2.5 on 2025-10-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Tauser',
                'verbose_name_plural': 'Tausers',
                'ordering': ['nombre'],
            },
        ),
    ]
