# Archivo compose para produccion (no montamos volúmenes)
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./app
    command: uv run python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:

# TODO: nginx/gunicorn
