# Archivo compose para produccion (no montamos volúmenes)
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports:
      - 8432:5432

  web:
    build: ./app
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             uv run gunicorn --chdir /app global_exchange_django.wsgi:application -w 4 -b 0.0.0.0:8000 --log-level=info"
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=global_exchange_django.settings
      - RUN_MIGRATIONS=1
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:1.25-alpine
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static:ro
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
