services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "7432:5432"
  web:
    build: ./app
    command: uv run python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    # volumes: TODO: montar entorno desarrollador, watch
    #   - ./app/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

# Nuevo servicios para tests
  test:
    build: ./app
    command: uv run python -m pytest
    working_dir: /app
    # volumes:
    #   - ./app/:/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data: