# Generated by Django 5.2.5 on 2025-08-31 13:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('simbolo', models.CharField(max_length=5, unique=True, verbose_name='Símbolo')),
                ('pais', models.CharField(blank=True, max_length=50, verbose_name='País')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Está Activa')),
                ('comision', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Comisión (%)')),
                ('tasa_actual', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Tasa Actual')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TasaDeCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_compra', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tasa de Compra')),
                ('tasa_venta', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Tasa de Venta')),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.moneda', verbose_name='Moneda')),
            ],
        ),
        migrations.AddField(
            model_name='moneda',
            name='tipo_de_cambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipodecambio', verbose_name='Tipo de Cambio'),
        ),
    ]
