# Generated by Django 5.2.5 on 2025-09-04 22:14

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Divisa",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        help_text="Código ISO 4217 de la divisa (ej. PYG, USD, EUR).",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la divisa (ej. Guaraní, Dólar Estadounidense).", max_length=50
                    ),
                ),
                ("simbolo", models.CharField(help_text="Símbolo de la divisa (ej. ₲, $, €).", max_length=5)),
            ],
            options={
                "verbose_name": "Divisa",
                "verbose_name_plural": "Divisas",
                "db_table": "divisa",
            },
        ),
        migrations.CreateModel(
            name="TasaCambio",
            fields=[
                (
                    "id_tasa_cambio",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único para la tasa de cambio.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="El valor de la divisa de origen en términos de la divisa de destino.",
                        max_digits=9,
                    ),
                ),
                (
                    "comision_compra",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0.00"),
                        help_text="Monto de comisión por compra en la divisa de destino (Guaraníes).",
                        max_digits=4,
                    ),
                ),
                (
                    "comision_venta",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0.00"),
                        help_text="Monto de comisión por venta en la divisa de destino (Guaraníes).",
                        max_digits=4,
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateField(auto_now=True, help_text="Fecha y hora de la última actualización de la tasa."),
                ),
                ("fecha_vigencia", models.DateField(help_text="Fecha a partir de la cual esta tasa es válida.")),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Indica si la tasa de cambio está activa o ha sido desactivada."
                    ),
                ),
                (
                    "hora_vigencia",
                    models.TimeField(
                        blank=True, help_text="Hora en la que la tasa de cambio entra en vigencia.", null=True
                    ),
                ),
                (
                    "divisa_destino",
                    models.ForeignKey(
                        help_text="La divisa a la cual se va a convertir.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasas_destino",
                        to="operaciones.divisa",
                    ),
                ),
                (
                    "divisa_origen",
                    models.ForeignKey(
                        help_text="La divisa que se va a intercambiar.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasas_origen",
                        to="operaciones.divisa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tasa de Cambio",
                "verbose_name_plural": "Tasas de Cambio",
                "db_table": "tasa_cambio",
                "unique_together": {("divisa_origen", "divisa_destino")},
            },
        ),
    ]
