# Generated by Django 5.2.5 on 2025-08-31 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='tipo_de_cambio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.tipodecambio', verbose_name='Tipo de Cambio'),
        ),
        migrations.AlterField(
            model_name='tipodecambio',
            name='nombre',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta')], max_length=50, verbose_name='Nombre'),
        ),
    ]
