# Generated by Django 5.2.5 on 2025-09-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_divisa_remove_moneda_tipo_de_cambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasacambio',
            name='hora_vigencia',
            field=models.TimeField(blank=True, help_text='Hora en la que la tasa de cambio entra en vigencia.', null=True),
        ),
    ]
