# Generated by Django 5.2.5 on 2025-09-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0002_crea_moneda_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasacambio",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True, help_text="Fecha y hora de la última actualización de la tasa."),
        ),
    ]
