# Generated by Django 5.2.5 on 2025-09-04 21:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_divisa_remove_moneda_tipo_de_cambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasacambio',
            name='hora_vigencia',
            field=models.TimeField(blank=True, help_text='Hora en la que la tasa de cambio entra en vigencia.', null=True),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='comision_compra',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), help_text='Monto de comisión por compra en la divisa de destino (Guaraníes).', max_digits=4),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='comision_venta',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), help_text='Monto de comisión por venta en la divisa de destino (Guaraníes).', max_digits=4),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='divisa_destino',
            field=models.ForeignKey(help_text='La divisa a la cual se va a convertir.', on_delete=django.db.models.deletion.PROTECT, related_name='tasas_destino', to='operaciones.divisa'),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='divisa_origen',
            field=models.ForeignKey(help_text='La divisa que se va a intercambiar.', on_delete=django.db.models.deletion.PROTECT, related_name='tasas_origen', to='operaciones.divisa'),
        ),
        migrations.AlterField(
            model_name='tasacambio',
            name='valor',
            field=models.DecimalField(decimal_places=3, help_text='El valor de la divisa de origen en términos de la divisa de destino.', max_digits=9),
        ),
    ]
