# Generated by Django 5.2.5 on 2025-09-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_divisa_estado_alter_divisa_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisa',
            name='estado',
            field=models.CharField(choices=[('Activa', 'activa'), ('Inactiva', 'inactiva')], default='Activa', max_length=10),
        ),
    ]
