# Generated by Django 5.2.5 on 2025-09-05 16:15

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0003_alter_tasacambio_fecha_actualizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasacambio",
            name="comision_compra",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Monto de comisión por compra en la divisa de destino (Guaraníes).",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="tasacambio",
            name="comision_venta",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Monto de comisión por venta en la divisa de destino (Guaraníes).",
                max_digits=4,
            ),
        ),
    ]
