# Generated by Django 5.2.5 on 2025-09-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_alter_divisa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='Activa', max_length=10),
        ),
    ]
