# Generated by Django 5.2.5 on 2025-09-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0004_alter_tasacambio_comision_compra_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasacambio",
            name="comision_compra",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Monto de comisión por compra en la divisa de destino (Guaraníes).",
                max_digits=7,
            ),
        ),
        migrations.AlterField(
            model_name="tasacambio",
            name="comision_venta",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Monto de comisión por venta en la divisa de destino (Guaraníes).",
                max_digits=7,
            ),
        ),
    ]
