# Generated by Django 5.2.5 on 2025-09-05 19:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0005_alter_tasacambio_comision_compra_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TasaCambioHistorial",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("valor", models.DecimalField(decimal_places=3, max_digits=9)),
                ("comision_compra", models.DecimalField(decimal_places=3, max_digits=7)),
                ("comision_venta", models.DecimalField(decimal_places=3, max_digits=7)),
                ("fecha_vigencia", models.DateField()),
                ("hora_vigencia", models.TimeField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "motivo",
                    models.CharField(
                        help_text="Motivo del cambio (ej. Creación, Edición, Desactivación)", max_length=255
                    ),
                ),
                (
                    "divisa_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasas_historial_destino",
                        to="operaciones.divisa",
                    ),
                ),
                (
                    "divisa_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasas_historial_origen",
                        to="operaciones.divisa",
                    ),
                ),
                (
                    "tasa_cambio_original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="operaciones.tasacambio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Tasa de Cambio",
                "verbose_name_plural": "Historial de Tasas de Cambio",
                "db_table": "tasa_cambio_historial",
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
