# Generated by Django 5.2.5 on 2025-09-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_tasacambiohistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='Activa', max_length=10),
        ),
        migrations.AlterField(
            model_name='divisa',
            name='codigo',
            field=models.CharField(help_text='(ej. PYG, USD, EUR).', max_length=3, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='divisa',
            name='nombre',
            field=models.CharField(help_text='(ej. Guaraní, Dólar Estadounidense).', max_length=50),
        ),
        migrations.AlterField(
            model_name='divisa',
            name='simbolo',
            field=models.CharField(help_text='(ej. ₲, $, €).', max_length=5),
        ),
    ]
