# Generated by Django 5.2.5 on 2025-09-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_divisa_estado_alter_divisa_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisa',
            name='simbolo',
            field=models.CharField(blank=True, default='', help_text='(ej. ₲, $, €).', max_length=5),
        ),
    ]
