# Generated by Django 5.2.5 on 2025-09-24 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0007_divisa_estado_alter_divisa_codigo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasacambio",
            name="fecha_vigencia",
        ),
        migrations.RemoveField(
            model_name="tasacambio",
            name="hora_vigencia",
        ),
        migrations.RemoveField(
            model_name="tasacambiohistorial",
            name="fecha_vigencia",
        ),
        migrations.RemoveField(
            model_name="tasacambiohistorial",
            name="hora_vigencia",
        ),
    ]
