# Generated by Django 5.2.5 on 2025-09-25 00:03

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0009_remove_tasacambio_fecha_vigencia_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasacambiohistorial",
            old_name="valor",
            new_name="precio_base",
        ),
        migrations.RemoveField(
            model_name="tasacambio",
            name="valor",
        ),
        migrations.AddField(
            model_name="tasacambio",
            name="precio_base",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.0"),
                help_text="El precio base de la divisa de origen en términos de la divisa de destino.",
                max_digits=9,
            ),
        ),
    ]
