# Generated by Django 5.2.5 on 2025-09-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0011_alter_tasacambio_precio_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasacambio",
            name="precio_base",
            field=models.DecimalField(
                decimal_places=3,
                help_text="El precio base de la divisa de origen en términos de la divisa de destino.",
                max_digits=9,
            ),
        ),
    ]
