# Generated by Django 5.2.5 on 2025-10-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_alter_tasacambio_precio_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisa',
            name='simbolo',
            field=models.CharField(blank=True, default='', help_text='(ej. ₲, $, €).', max_length=5),
        ),
    ]
