# Generated by Django 5.2.5 on 2025-10-31 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_alter_divisa_simbolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacambiohistorial',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
