# Generated by Django 5.2.5 on 2025-10-04 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilMFA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("secreto_totp", models.CharField(help_text="Secreto base32 para generar códigos TOTP", max_length=32)),
                (
                    "mfa_habilitado_login",
                    models.BooleanField(default=False, help_text="Si está habilitado MFA para el login del usuario"),
                ),
                (
                    "mfa_habilitado_transacciones",
                    models.BooleanField(
                        default=True, help_text="Si está habilitado MFA para confirmar transacciones (recomendado)"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_mfa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil MFA",
                "verbose_name_plural": "Perfiles MFA",
            },
        ),
        migrations.CreateModel(
            name="RegistroMFA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tipo_operacion",
                    models.CharField(
                        choices=[("login", "Login"), ("transaccion", "Confirmación de Transacción")],
                        help_text="Tipo de operación que requirió MFA",
                        max_length=20,
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[("exitoso", "Exitoso"), ("fallido", "Fallido"), ("expirado", "Código Expirado")],
                        help_text="Resultado del intento de autenticación",
                        max_length=20,
                    ),
                ),
                (
                    "direccion_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="Dirección IP desde donde se realizó el intento", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User agent del navegador")),
                (
                    "referencia_transaccion",
                    models.UUIDField(blank=True, help_text="ID de transacción si aplica", null=True),
                ),
                ("fecha_intento", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_mfa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro MFA",
                "verbose_name_plural": "Registros MFA",
                "ordering": ["-fecha_intento"],
            },
        ),
    ]
