# Generated by Django 5.2.5 on 2025-08-22 19:45

from django.db import migrations


def insertar_tipos_clientes(apps, schema_editor):
    TipoCliente = apps.get_model("usuarios", "TipoCliente")
    TipoCliente.objects.bulk_create([
        TipoCliente(nombre="Minorista"),
        TipoCliente(nombre="Corporativo"),
        TipoCliente(nombre="VIP"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(insertar_tipos_clientes),
    ]
