# Generated by Django 5.2.5 on 2025-09-04 18:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_tipocliente_descuento_sobre_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocliente',
            name='descuento_sobre_comision',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3),
        ),
    ]
