# Generated by Django 5.2.5 on 2025-09-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_tipocliente_descuento_sobre_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
