# Generated by Django 5.2.5 on 2025-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_preferencianotificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencianotificacion',
            name='frecuencia',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='daily', max_length=10),
        ),
    ]
