# Generated by Django 5.2.5 on 2025-10-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_preferencianotificacion_frecuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencianotificacion',
            name='frecuencia',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diario', max_length=10),
        ),
    ]
