# Generated by Django 5.2.5 on 2025-11-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_reportes', 'Ver reportes y dashboards'), ('generate_reportes', 'Generar reportes')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
