# Generated by Django 5.2.5 on 2025-09-22 15:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_alter_cliente_ruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('emisor_tarjeta', 'Emisor de Tarjeta'), ('proveedor_billetera', 'Proveedor de Billetera')], max_length=20)),
                ('comision_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('comision_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entidad Financiera',
                'verbose_name_plural': 'Entidades Financieras',
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('nombre', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('habilitado_para_pago', models.BooleanField(default=True, help_text='Indica si este medio financiero puede utilizarse para realizar pagos')),
                ('habilitado_para_cobro', models.BooleanField(default=False, help_text='Indica si este medio financiero puede utilizarse para recibir cobros')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_cuenta', models.CharField(max_length=30)),
                ('titular_cuenta', models.CharField(max_length=100)),
                ('documento_titular', models.CharField(max_length=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='usuarios.cliente')),
                ('entidad', models.ForeignKey(blank=True, help_text='Entidad bancaria', limit_choices_to={'activo': True, 'tipo': 'banco'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.entidadfinanciera')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'unique_together': {('cliente', 'numero_cuenta', 'entidad')},
            },
        ),
        migrations.CreateModel(
            name='BilleteraElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('habilitado_para_pago', models.BooleanField(default=True, help_text='Indica si este medio financiero puede utilizarse para realizar pagos')),
                ('habilitado_para_cobro', models.BooleanField(default=False, help_text='Indica si este medio financiero puede utilizarse para recibir cobros')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('identificador', models.CharField(help_text='Email, número de teléfono o ID de la billetera', max_length=100)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('email_asociado', models.EmailField(max_length=254)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='usuarios.cliente')),
                ('entidad', models.ForeignKey(blank=True, help_text='Proveedor de la billetera electrónica', limit_choices_to={'activo': True, 'tipo': 'proveedor_billetera'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.entidadfinanciera')),
            ],
            options={
                'verbose_name': 'Billetera Electrónica',
                'verbose_name_plural': 'Billeteras Electrónicas',
                'unique_together': {('cliente', 'entidad', 'identificador')},
            },
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('habilitado_para_pago', models.BooleanField(default=True, help_text='Indica si este medio financiero puede utilizarse para realizar pagos')),
                ('habilitado_para_cobro', models.BooleanField(default=False, help_text='Indica si este medio financiero puede utilizarse para recibir cobros')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('nombre_titular', models.CharField(max_length=100)),
                ('fecha_expiracion', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='usuarios.cliente')),
                ('entidad', models.ForeignKey(blank=True, help_text='Entidad emisora de la tarjeta (Visa, Mastercard, etc.)', limit_choices_to={'activo': True, 'tipo': 'emisor_tarjeta'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.entidadfinanciera')),
            ],
            options={
                'verbose_name': 'Tarjeta de Crédito',
                'verbose_name_plural': 'Tarjetas de Crédito',
                'unique_together': {('cliente', 'numero_tarjeta')},
            },
        ),
    ]
