# Generated by Django 5.2.5 on 2025-09-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_alter_cliente_ruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilleteraElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.CharField(choices=[('personal_pay', 'Personal Pay'), ('mango', 'Mango'), ('wally', 'Wally'), ('eko', 'Eko'), ('vaquita', 'Vaquita'), ('otros', 'Otros')], max_length=50)),
                ('identificador', models.CharField(help_text='Email, número de teléfono o ID de la billetera', max_length=100)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('email_asociado', models.EmailField(max_length=254)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Billetera Electrónica',
                'verbose_name_plural': 'Billeteras Electrónicas',
                'unique_together': {('cliente', 'proveedor', 'identificador')},
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_cuenta', models.CharField(max_length=30)),
                ('banco', models.CharField(max_length=100)),
                ('titular_cuenta', models.CharField(max_length=100)),
                ('documento_titular', models.CharField(max_length=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'unique_together': {('cliente', 'numero_cuenta', 'banco')},
            },
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('nombre_titular', models.CharField(max_length=100)),
                ('fecha_expiracion', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'Tarjeta de Crédito',
                'verbose_name_plural': 'Tarjetas de Crédito',
                'unique_together': {('cliente', 'numero_tarjeta')},
            },
        ),
    ]
