# Generated by Django 5.2.5 on 2025-09-18 13:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
        ('usuarios', '0007_alter_cliente_ruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadMedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('emisor_tarjeta', 'Emisor de Tarjeta'), ('proveedor_billetera', 'Proveedor de Billetera')], max_length=20)),
                ('comision_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de comisión para operaciones de compra (0.00-999.99)', max_digits=5)),
                ('comision_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de comisión para operaciones de venta (0.00-999.99)', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entidad de Medio de Pago',
                'verbose_name_plural': 'Entidades de Medios de Pago',
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('nombre', 'tipo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='billeteraelectronica',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cuentabancaria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='billeteraelectronica',
            name='entidad',
            field=models.ForeignKey(blank=True, help_text='Proveedor de la billetera electrónica', limit_choices_to={'activo': True, 'tipo': 'proveedor_billetera'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.entidadmediopago'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='entidad',
            field=models.ForeignKey(blank=True, help_text='Entidad bancaria', limit_choices_to={'activo': True, 'tipo': 'banco'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.entidadmediopago'),
        ),
        migrations.AddField(
            model_name='tarjetacredito',
            name='entidad',
            field=models.ForeignKey(blank=True, help_text='Entidad emisora de la tarjeta (Visa, Mastercard, etc.)', limit_choices_to={'activo': True, 'tipo': 'emisor_tarjeta'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.entidadmediopago'),
        ),
        migrations.AlterUniqueTogether(
            name='billeteraelectronica',
            unique_together={('cliente', 'entidad', 'identificador')},
        ),
        migrations.AlterUniqueTogether(
            name='cuentabancaria',
            unique_together={('cliente', 'numero_cuenta', 'entidad')},
        ),
        migrations.RemoveField(
            model_name='billeteraelectronica',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='cuentabancaria',
            name='banco',
        ),
    ]
