# Generated by Django 5.2.5 on 2025-09-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_poblar_entidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteTransacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario', models.DecimalField(decimal_places=0, help_text='Límite máximo de transacciones por día en guaraníes', max_digits=15)),
                ('limite_mensual', models.DecimalField(decimal_places=0, help_text='Límite máximo de transacciones por mes en guaraníes', max_digits=15)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de cuando se estableció este límite')),
            ],
            options={
                'verbose_name': 'Límite de Transacciones',
                'verbose_name_plural': 'Límites de Transacciones',
                'db_table': 'limite_transacciones',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
