# Generated by Django 5.2.5 on 2025-09-25 06:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operaciones", "0012_alter_tasacambio_precio_base"),
        ("transacciones", "0003_limitetransacciones"),
        ("usuarios", "0007_alter_cliente_ruc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id_transaccion",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la transacción",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_operacion",
                    models.CharField(
                        choices=[("compra", "Compra"), ("venta", "Venta")],
                        help_text="Tipo de operación (compra o venta)",
                        max_length=50,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                            ("fallida", "Fallida"),
                        ],
                        default="pendiente",
                        help_text="Estado actual de la transacción",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, help_text="Fecha y hora de creación de la transacción"),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(blank=True, help_text="Fecha y hora del pago (opcional)", null=True),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(auto_now=True, help_text="Fecha y hora de última actualización"),
                ),
                (
                    "tasa_aplicada",
                    models.DecimalField(
                        decimal_places=8, help_text="Tasa de cambio aplicada en la transacción", max_digits=15
                    ),
                ),
                (
                    "monto_origen",
                    models.DecimalField(decimal_places=8, help_text="Monto en la divisa de origen", max_digits=15),
                ),
                (
                    "monto_destino",
                    models.DecimalField(decimal_places=8, help_text="Monto en la divisa de destino", max_digits=15),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente que realiza la transacción",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "divisa_destino",
                    models.ForeignKey(
                        help_text="Divisa de destino de la transacción",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones_destino",
                        to="operaciones.divisa",
                    ),
                ),
                (
                    "divisa_origen",
                    models.ForeignKey(
                        help_text="Divisa de origen de la transacción",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones_origen",
                        to="operaciones.divisa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuario que procesa la transacción",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones_procesadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción",
                "verbose_name_plural": "Transacciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
