# Generated by Django 5.2.5 on 2025-09-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('fallida', 'Fallida')], default='pendiente', help_text='Estado actual de la transacción', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto_destino',
            field=models.DecimalField(decimal_places=8, help_text='Monto en la divisa de destino', max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto_origen',
            field=models.DecimalField(decimal_places=8, help_text='Monto en la divisa de origen', max_digits=20),
        ),
    ]
