# Generated by Django 5.2.5 on 2025-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_alter_transaccion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='medio_cobro',
            field=models.CharField(blank=True, help_text='Identificador del medio de cobro utilizado (efectivo, tarjeta_X, cuenta_X, billetera_X)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='medio_pago',
            field=models.CharField(blank=True, help_text='Identificador del medio de pago utilizado (efectivo, tarjeta_X, cuenta_X, billetera_X)', max_length=100, null=True),
        ),
    ]
