# Generated by Django 5.2.5 on 2025-09-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transacciones", "0006_transaccion_medio_cobro_transaccion_medio_pago"),
        ("usuarios", "0007_alter_cliente_ruc"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_payment_intent_id",
                    models.CharField(help_text="ID del PaymentIntent de Stripe", max_length=100, unique=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, help_text="ID del customer en Stripe", max_length=100, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Monto del pago en la moneda especificada", max_digits=12
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="USD", help_text="Moneda del pago (USD, EUR, etc.)", max_length=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requires_payment_method", "Requiere método de pago"),
                            ("requires_confirmation", "Requiere confirmación"),
                            ("requires_action", "Requiere acción"),
                            ("processing", "Procesando"),
                            ("requires_capture", "Requiere captura"),
                            ("canceled", "Cancelado"),
                            ("succeeded", "Exitoso"),
                        ],
                        default="requires_payment_method",
                        help_text="Estado del pago en Stripe",
                        max_length=30,
                    ),
                ),
                (
                    "payment_method_id",
                    models.CharField(
                        blank=True, help_text="ID del método de pago en Stripe", max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Fecha de creación del pago")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Fecha de última actualización")),
                (
                    "metadata",
                    models.TextField(blank=True, help_text="Metadatos adicionales del pago (JSON)", null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente que realiza el pago",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_payments",
                        to="usuarios.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago Stripe",
                "verbose_name_plural": "Pagos Stripe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="transaccion",
            name="stripe_payment",
            field=models.ForeignKey(
                blank=True,
                help_text="Pago Stripe asociado a la transacción (solo para pagos internacionales)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transacciones.stripepayment",
            ),
        ),
    ]
