# Generated by Django 5.2.5 on 2025-09-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transacciones", "0006_transaccion_medio_cobro_transaccion_medio_pago"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaccion",
            name="cambio_cotizacion_notificado",
            field=models.BooleanField(
                default=False, help_text="Indica si se notificó al cliente sobre el cambio de cotización"
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="fecha_vencimiento_cotizacion",
            field=models.DateTimeField(
                blank=True, help_text="Fecha límite para usar la cotización original", null=True
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="motivo_cancelacion",
            field=models.TextField(
                blank=True, help_text="Motivo detallado de la cancelación de la transacción", null=True
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="tasa_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Tasa de cambio actual (se actualiza al verificar cotización)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="tasa_original",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Tasa de cambio original al momento de crear la transacción",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaccion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                    ("cancelada_cotizacion", "Cancelada por cambio de cotización"),
                    ("vencida", "Vencida por cambio de cotización"),
                    ("anulada", "Anulada"),
                ],
                default="pendiente",
                help_text="Estado actual de la transacción",
                max_length=20,
            ),
        ),
    ]
