# Generated by Django 5.2.5 on 2025-09-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transacciones", "0007_stripepayment_transaccion_stripe_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaccion",
            name="cambio_cotizacion_notificado",
            field=models.BooleanField(
                default=False, help_text="Indica si se ha notificado al cliente sobre cambios en la cotización"
            ),
        ),
        migrations.AlterField(
            model_name="transaccion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("completada", "Completada"),
                    ("cancelada", "Cancelada"),
                    ("anulada", "Anulada"),
                    ("disputada", "Disputada"),
                    ("reembolsada", "Reembolsada"),
                ],
                default="pendiente",
                help_text="Estado actual de la transacción",
                max_length=20,
            ),
        ),
    ]
