# Generated by Django 5.2.5 on 2025-10-16 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transacciones", "0007_transaccion_cambio_cotizacion_notificado_and_more"),
        ("usuarios", "0008_crear_y_asignar_permisos_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_payment_intent_id",
                    models.CharField(help_text="ID del PaymentIntent de Stripe", max_length=100, unique=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, help_text="ID del customer en Stripe", max_length=100, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Monto del pago en la moneda especificada", max_digits=12
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="USD", help_text="Moneda del pago (USD, EUR, etc.)", max_length=3),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requires_payment_method", "Requiere método de pago"),
                            ("requires_confirmation", "Requiere confirmación"),
                            ("requires_action", "Requiere acción"),
                            ("processing", "Procesando"),
                            ("requires_capture", "Requiere captura"),
                            ("canceled", "Cancelado"),
                            ("succeeded", "Exitoso"),
                            ("failed", "Fallido"),
                        ],
                        default="requires_payment_method",
                        help_text="Estado del pago en Stripe",
                        max_length=30,
                    ),
                ),
                (
                    "payment_method_id",
                    models.CharField(
                        blank=True, help_text="ID del método de pago en Stripe", max_length=100, null=True
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True, help_text="Marca de la tarjeta (visa, mastercard, etc.)", max_length=20, null=True
                    ),
                ),
                (
                    "card_last4",
                    models.CharField(blank=True, help_text="Últimos 4 dígitos de la tarjeta", max_length=4, null=True),
                ),
                (
                    "card_country",
                    models.CharField(
                        blank=True, help_text="País emisor de la tarjeta (código ISO)", max_length=2, null=True
                    ),
                ),
                (
                    "save_payment_method",
                    models.BooleanField(default=False, help_text="Si el cliente solicitó guardar la tarjeta"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True, help_text="Fecha de creación del pago")),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True, help_text="Fecha de última actualización")),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Metadatos adicionales del pago")),
                (
                    "log_operaciones",
                    models.TextField(blank=True, help_text="Log JSON de todas las operaciones realizadas", null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente que realiza el pago",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_payments",
                        to="usuarios.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago Stripe",
                "verbose_name_plural": "Pagos Stripe",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.AddField(
            model_name="transaccion",
            name="stripe_payment",
            field=models.ForeignKey(
                blank=True,
                help_text="Pago con Stripe asociado a esta transacción",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transacciones",
                to="transacciones.stripepayment",
            ),
        ),
        migrations.CreateModel(
            name="TarjetaExtranjera",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stripe_payment_method_id",
                    models.CharField(help_text="ID del PaymentMethod en Stripe", max_length=100, unique=True),
                ),
                ("stripe_customer_id", models.CharField(help_text="ID del Customer en Stripe", max_length=100)),
                ("brand", models.CharField(help_text="Marca de la tarjeta (visa, mastercard, etc.)", max_length=20)),
                ("last4", models.CharField(help_text="Últimos 4 dígitos de la tarjeta", max_length=4)),
                ("alias", models.CharField(help_text="Alias personalizado para la tarjeta", max_length=50)),
                ("activo", models.BooleanField(default=True, help_text="Indica si la tarjeta está activa para uso")),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, help_text="Fecha de registro de la tarjeta"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        help_text="Cliente propietario de la tarjeta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarjetas_extranjeras",
                        to="usuarios.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta Extranjera",
                "verbose_name_plural": "Tarjetas Extranjeras",
                "ordering": ["-fecha_creacion"],
                "unique_together": {("cliente", "stripe_payment_method_id")},
            },
        ),
    ]
