# Generated by Django 5.2.5 on 2025-10-16 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transacciones", "0008_stripepayment_transaccion_stripe_payment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripepayment",
            name="save_payment_method",
        ),
    ]
