# Generated by Django 5.2.5 on 2025-10-20 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0009_remove_stripepayment_save_payment_method'),
        ('usuarios', '0008_crear_y_asignar_permisos_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='codigo_verificacion',
            field=models.CharField(blank=True, help_text='Código único de verificación generado para el tauser', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de generación del código de verificación', null=True),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente que realiza el pago', on_delete=django.db.models.deletion.PROTECT, related_name='stripe_payments', to='usuarios.cliente'),
        ),
    ]
