# Generated by Django 5.2.5 on 2025-10-18 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0009_remove_stripepayment_save_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='codigo_verificacion',
            field=models.CharField(blank=True, help_text='Código único de verificación generado para el tauser', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario_responsable',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable de procesar la transacción en el tauser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
