# Generated by Django 5.2.5 on 2025-10-18 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0010_add_usuario_responsable_codigo_verificacion'),
        ('usuarios', '0008_crear_y_asignar_permisos_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente que realiza el pago', on_delete=django.db.models.deletion.PROTECT, related_name='stripe_payments', to='usuarios.cliente'),
        ),
    ]
