# Generated by Django 5.2.5 on 2025-10-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0010_transaccion_codigo_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de finalización de la transacción', null=True),
        ),
    ]
