# Generated by Django 5.2.5 on 2025-10-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0011_alter_stripepayment_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de generación del código de verificación', null=True),
        ),
    ]
