# Generated by Django 5.2.5 on 2025-10-20 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0002_add_tauser_permissions'),
        ('transacciones', '0011_transaccion_fecha_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tauser',
            field=models.ForeignKey(blank=True, help_text='Terminal de autoservicio donde se procesa la transacción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='tauser.tauser'),
        ),
    ]
