# Generated by Django 5.2.5 on 2025-10-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0010_alter_stripepayment_cliente'),
        ('transacciones', '0012_transaccion_tauser'),
    ]

    operations = [
    ]
