# Generated by Django 5.2.5 on 2025-10-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transacciones", "0013_merge_20251030_1551"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaccion",
            name="cdc_factura",
            field=models.CharField(
                blank=True,
                help_text="Código de Control (CDC) de la factura electrónica generada",
                max_length=44,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="transaccion",
            name="fecha_facturacion",
            field=models.DateTimeField(
                blank=True, help_text="Fecha y hora de generación de la factura electrónica", null=True
            ),
        ),
    ]
