# Generated by Django 5.2.5 on 2025-11-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0014_transaccion_cdc_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='comision_aplicada',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Comisión (compra o venta) aplicada al momento de la transacción', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='ganancia_calculada',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Ganancia en PYG calculada al momento de completar la transacción', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='precio_base_aplicado',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Precio base de la divisa al momento de la transacción (histórico)', max_digits=15, null=True),
        ),
    ]
